name: Deploy to VPS with Password

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Run git pull on VPS
        run: |
          sshpass -p "Daffa2!3" ssh -o StrictHostKeyChecking=no senpro@103.226.138.66 "cd backend/BE-senpronext && git pull"
